services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.11.3
    privileged: true
    restart: always
    environment:
      - node.name=es01
      - ELASTIC_PASSWORD=123456
      - bootstrap.memory_lock=false
      #以单一节点模式启动
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - TZ='Asia/Shanghai'
      #设置使用jvm内存大小
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: logstash:7.6.2
    container_name: logstash
    ports:
      - 4560:4560
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      #挂载logstash的配置文件
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    links:
      #可以用es这个域名访问elasticsearch服务
      - elasticsearch:es
      -
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    ports:
      - 5601:5601
    privileged: true
    links:
      #可以用es这个域名访问elasticsearch服务
      - elasticsearch:es
    depends_on:
      - elasticsearch
    environment:
      #设置访问elasticsearch的地址
      - elasticsearch.hosts=http://es:9200
