services:
  xxl-job-admin:
    image: longfei59418/xxl-job-admin-arm:2.4.0
    restart: always
    ports:
      - "8040:8080"
    environment:
      PARAMS: '
        --spring.datasource.url=jdbc:mysql://172.16.14.133:3306/xxl_job?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        --spring.datasource.username=root
        --spring.datasource.password=123456
        --xxl.job.accessToken=xxl-job'
    volumes:
      - ./logs:/data/applogs
