version: "3"

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    hostname: kafka-ui
    privileged: true
    restart: always
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - AUTH_TYPE=LOGIN_FORM
      - SPRING_SECURITY_USER_NAME=zdww
      - SPRING_SECURITY_USER_PASSWORD=meiyoumima
    #volumes:
    #  - ~/conf/config.yml:/etc/kafkaui/dynamic_config.yaml
    ports:
      - "58080:8080"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
