version: '3.5'
services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-enterprise-server:7.0.1-ubuntu2204
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./data:/data/db
    command:
      - "--auth"
