apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-09-13T08:31:50Z"
  labels:
    app: webz
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-09-13T08:31:50Z"
  name: web1
  namespace: default
  resourceVersion: "6375"
  selfLink: /api/v1/namespaces/default/services/web1
  uid: 422dbe8e-1160-4263-9366-1c3b1019231a
spec:
  clusterIP: 10.111.213.217
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31255
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
